export const mentionsStyles = {
  control: {
    minHeight: 44,
    border: "none",
    outline: "none",
    background: "transparent",
    width: "100%",
  },
  "&multiLine": {
    highlighter: {
      padding: "10px 16px",
      fontSize: 16,
      lineHeight: 1.6,
      maxHeight: 180,
      overflow: "hidden",
      color: "transparent",
      whiteSpace: "pre-wrap",
    },
    input: {
      padding: "10px 16px",
      outline: "none",
      fontSize: 16,
      lineHeight: 1.6,
      minHeight: 44,
      maxHeight: 180,
      overflowY: "auto",
      resize: "none",
      boxSizing: "border-box",
      color: "inherit",
      backgroundColor: "transparent",
    },
  },
  "&singleLine": {
    highlighter: {
      padding: "10px 16px",
      fontSize: 16,
      lineHeight: 1.6,
      color: "transparent",
      whiteSpace: "pre",
    },
    input: {
      padding: "10px 16px",
      outline: "none",
      fontSize: 16,
      lineHeight: 1.6,
      color: "inherit",
      backgroundColor: "transparent",
    },
  },
} as const;
