"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { UIMessage } from "ai";
import { Loader } from "lucide-react";
import { usePrivy } from "@privy-io/react-auth";
import { useUserProvider } from "@/providers/UserProvder";
import { useOrganization } from "@/providers/OrganizationProvider";
import useAccountOrganizations from "@/hooks/useAccountOrganizations";
import { buildOrgRepoUrl } from "@/lib/recoupable/buildOrgRepoUrl";
import { buildPersonalRepoUrl } from "@/lib/recoupable/buildPersonalRepoUrl";
import { createSession } from "@/lib/sessions/createSession";
import { createSandbox } from "@/lib/sandboxes/createSandbox";
import { Chat } from "@/components/VercelChat/chat";

interface NewChatBootstrapProps {
  /** Chat row id generated by the server page (`generateUUID`). */
  id: string;
  initialMessages?: UIMessage[];
}

type BootstrapState =
  | { status: "idle" | "bootstrapping" }
  | { status: "ready"; sessionId: string }
  | { status: "error"; message: string };

/**
 * Client-side bootstrap for new chats. Provisions a session +
 * sandbox on recoup-api before mounting `<Chat>` so the workflow
 * transport (`/api/chat/workflow`) has the `sessionId` its validator
 * requires (recoupable/chat#1747 Phase 1 + 3).
 *
 * Mounted by `app/chat/page.tsx` (server) which generates the chat id
 * and forwards it here; this component owns everything that needs
 * Privy/the API base URL.
 *
 * `cloneUrl` resolution mirrors open-agents' rule: if the
 * `OrganizationProvider` has an active org, build the org repo URL;
 * otherwise fall back to the per-account "personal" repo URL.
 */
export default function NewChatBootstrap({
  id,
  initialMessages,
}: NewChatBootstrapProps) {
  const { authenticated, getAccessToken } = usePrivy();
  const { userData } = useUserProvider();
  const { selectedOrgId } = useOrganization();
  const { data: organizations } = useAccountOrganizations();
  const [state, setState] = useState<BootstrapState>({ status: "idle" });

  // Guard against React StrictMode double-mount running the bootstrap
  // twice — the inner createSession/createSandbox calls are not
  // idempotent (each POST would mint a fresh row + sandbox).
  const startedRef = useRef(false);

  const cloneUrl = useMemo(() => {
    if (selectedOrgId) {
      const org = organizations?.find(
        (o) => o.organization_id === selectedOrgId,
      );
      if (!org?.organization_name) return null;
      return buildOrgRepoUrl({
        organizationId: org.organization_id,
        organizationName: org.organization_name,
      });
    }
    if (userData?.account_id && userData?.name) {
      return buildPersonalRepoUrl({
        accountId: userData.account_id,
        accountName: userData.name,
      });
    }
    return null;
  }, [selectedOrgId, organizations, userData?.account_id, userData?.name]);

  useEffect(() => {
    if (!authenticated || !cloneUrl) return;
    if (startedRef.current) return;
    if (state.status !== "idle") return;

    startedRef.current = true;
    setState({ status: "bootstrapping" });

    void (async () => {
      try {
        const accessToken = await getAccessToken();
        if (!accessToken) {
          throw new Error("Please sign in to start a chat");
        }

        const { session } = await createSession({ cloneUrl }, accessToken);
        await createSandbox(cloneUrl, session.id, accessToken);

        setState({ status: "ready", sessionId: session.id });
      } catch (error) {
        startedRef.current = false;
        const message =
          error instanceof Error
            ? error.message
            : "Failed to start a new chat. Please try again.";
        setState({ status: "error", message });
      }
    })();
  }, [authenticated, cloneUrl, getAccessToken, state.status]);

  if (state.status === "ready") {
    return (
      <Chat
        id={id}
        sessionId={state.sessionId}
        initialMessages={initialMessages}
      />
    );
  }

  if (state.status === "error") {
    return (
      <div className="flex size-full items-center justify-center text-sm text-red-600">
        {state.message}
      </div>
    );
  }

  return (
    <div className="flex size-full items-center justify-center">
      <Loader className="size-5 animate-spin text-muted-foreground" />
    </div>
  );
}
