import { z } from "zod";
import { tool } from "ai";
import { createSegments } from "@/lib/segments/createSegments";

const schema = z.object({
  artist_account_id: z
    .string()
    .min(
      1,
      "artist_account_id is required and should be pulled from the system prompt. Never request this from the user.",
    ),
  prompt: z
    .string()
    .min(
      1,
      "Prompt is required and should be generated by the system if not provided. Never ask the user for this parameter; if not provided, make it up, but do not ever ask the user for it.",
    ),
});

const createSegmentsTool = tool({
  description:
    "Create segments by analyzing fan data and generating segment names. This tool fetches all fans for an artist, generates segment names based on the provided prompt, and saves the segments to the database. If required information is missing (social accounts or fan data), the tool will provide step-by-step instructions to gather the missing prerequisites using other available tools.",
  inputSchema: schema,
  execute: async ({ artist_account_id, prompt }) => {
    return await createSegments({ artist_account_id, prompt });
  },
});

export default createSegmentsTool;
